FROM python:alpine

RUN apk add --no-cache groff less mailcap

LABEL io.whalebrew.name 'deployto'
LABEL io.whalebrew.config.environment '["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_SESSION_TOKEN", "AWS_DEFAULT_REGION", "AWS_PROFILE", "AWS_CONFIG_FILE"]'
LABEL io.whalebrew.config.volumes '["~/.aws:/.aws"]'

WORKDIR /deployto

RUN pip install boto3==1.6.4 pyyaml==3.12 schematics==2.0.1

COPY ./ ./

RUN pip install .

ENTRYPOINT ["deployto"]